export { LandingPage } from "./LandingPage/LandingPage";
export { Home } from "./Home/Home";
export { Labels } from "./Labels/Labels";
export { Archive } from "./Archive/Archive";
export { Trash } from "./Trash/Trash";
export { Profile } from "./Profile/Profile";
export { Login } from "./Login/Login";
export { Signup } from "./Signup/Signup";
export { MockAPI } from "./MockAPI/MockAPI";
